In [28]:
import tensorflow as tf

In [3]:
tf.__version__

'1.13.0-rc1'

In [4]:
hello = tf.constant("hello")
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [5]:
world = tf.constant("World")
world

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
 with tf.Session() as sess:
        result = sess.run(hello+world)

In [9]:
result

b'helloWorld'

In [10]:
var1 = tf.constant(10)
var2 = tf.constant(30)

var1 + var2

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [11]:
with tf.Session() as sess:
    result = sess.run(var1+var2)

In [12]:
result

40

In [13]:
const = tf.constant(10)

In [33]:
mat_1 = tf.fill((5,5),10)

# output
# [[10 10 10 10 10]
#  [10 10 10 10 10]
#  [10 10 10 10 10]
#  [10 10 10 10 10]
#  [10 10 10 10 10]]


In [15]:
zeros = tf.zeros((5,5))

#output 
# [[0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]]


<tf.Tensor 'zeros:0' shape=(5, 5) dtype=float32>

In [36]:
ones = tf.ones((5,5))

#output 
# [[1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]]


In [39]:
randn = tf.random_normal((4,4), mean=0, stddev=1.0) #normal dstribution

#output
# [[ 1.3528444   1.9706491  -2.9234462  -0.7638081 ]
#  [-0.11207984  2.0881774  -0.5741538   0.1687726 ]
#  [-0.36480325  2.4304276   0.26898375 -0.0402476 ]
#  [-1.0585244   0.94118494 -1.2755234   1.7524296 ]]


In [18]:
randu = tf.random_uniform((4,4), minval=0, maxval=1) #uniform distribution

#output
# [[0.8449396  0.11132193 0.68254864 0.28614902]
#  [0.49649584 0.5770695  0.23227024 0.587958  ]
#  [0.03491473 0.4098816  0.92555606 0.13194072]
#  [0.69335175 0.31644475 0.6709788  0.66748667]]


In [42]:
myops = [const, mat_1, zeros, ones, randn, randu]
myops

[<tf.Tensor 'Const_4:0' shape=() dtype=int32>,
 <tf.Tensor 'Fill_2:0' shape=(5, 5) dtype=int32>,
 <tf.Tensor 'zeros:0' shape=(5, 5) dtype=float32>,
 <tf.Tensor 'ones_2:0' shape=(5, 5) dtype=float32>,
 <tf.Tensor 'random_normal_1:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>]

In [44]:
with tf.Session() as sess:
    result = sess.run(myops)
    print(result)


[10, array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]]), array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32), array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32), array([[ 0.07074768,  0.44289342,  0.17759322, -1.0041325 ],
       [-0.36544147,  0.83512646,  0.68504083, -2.1949146 ],
       [-1.1495737 ,  0.8690187 ,  0.49160063, -1.1674874 ],
       [ 0.1777285 ,  0.9367899 , -1.0541655 , -0.7722622 ]],
      dtype=float32), array([[0.25063705, 0.33984768, 0.3140663 , 0.7935692 ],
       [0.7851356 , 0.3785559 , 0.15913332, 0.68978333],
       [0.6738666 , 0.47559226, 0.67696726, 0.66681707],
       [0.5421804 , 0.55404663, 0.54536617, 0.0200119 ]], dtype=float32)]


In [20]:
sess = tf.InteractiveSession()

In [21]:
for op in myops:
#     print(sess.run(op))
    print(op.eval()) #
    print("\n")

10


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[ 0.14061095 -1.7857347  -0.25391906 -0.6744037 ]
 [ 0.19787367  0.067743    0.06061641 -0.9052059 ]
 [ 0.5022889   0.4375519   0.19083269  0.57796985]
 [ 0.08303713  0.89130914  1.2621524  -1.1117582 ]]


[[0.36442077 0.0051235  0.91495574 0.8060101 ]
 [0.39075816 0.47467315 0.41400182 0.01170897]
 [0.7137455  0.6104454  0.82351744 0.417485  ]
 [0.12349093 0.8497832  0.4400555  0.28436232]]




In [22]:
a = tf.constant([[1,2],[3,4]])

In [23]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [24]:
b = tf.constant([[10],[100]])

In [25]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [26]:
result = tf.matmul(a,b)

In [27]:
sess.run(result)

array([[210],
       [430]])