In [2]:
#creating the perceptron or Neuron

In [14]:
import tensorflow as tf
import numpy as np

In [15]:
np.random.seed(101)
tf.set_random_seed(101)

In [16]:
rand_a = np.random.uniform(0,100,(5,5))#will create the uniform type matrix

rand_a

array([[51.63986277, 57.06675869,  2.84742265, 17.15216562, 68.52769817],
       [83.38968626, 30.69662197, 89.36130797, 72.15438618, 18.99389542],
       [55.42275911, 35.2131954 , 18.18924027, 78.56017619, 96.54832224],
       [23.23536618,  8.35614337, 60.35484223, 72.89927573, 27.62388285],
       [68.53063288, 51.78674742,  4.84845374, 13.78692376, 18.69674261]])

In [5]:
rand_b = np.random.uniform(0,100,(5,1))
rand_b

array([[99.43179012],
       [52.06653967],
       [57.87895355],
       [73.48190583],
       [54.19617722]])

In [6]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [7]:
add = a+b

In [13]:
# with tf.Session() as sess:
#     result = sess.run(add)

In [35]:
mul = a*b

In [39]:
with tf.Session() as sess:
    add_result = sess.run(add, feed_dict={a:20, b:30})
    print(add_result)

50.0


In [46]:
with tf.Session() as sess:
    add_result = sess.run(add, feed_dict={a:rand_a, b:rand_b})
    print(add_result)
    print("\n")
    mult = sess.run(mul, feed_dict={a:rand_a, b:rand_b})
    print(mult)
    

[[120.16756  135.02954   82.33649  141.00116  123.79425 ]
 [ 76.06065  112.48952   92.27995   75.256    135.62692 ]
 [ 99.395744  26.08279   11.203566  63.202267  75.7467  ]
 [ 44.776047  85.6828    68.93891   22.00062   30.93909 ]
 [ 87.22444  167.95949  120.59424  126.40665  142.0096  ]]


[[3538.7607  4306.232   1585.1693  4614.6055  3726.0427 ]
 [1083.9199  3162.797   2009.5029  1038.0009  4483.1743 ]
 [ 274.91388   66.16091   23.79347  171.85574  207.57504]
 [ 473.80942 1175.4489   888.2549    83.16148  236.4756 ]
 [1281.2448  6813.8315  3568.      3966.311   5035.5454 ]]
